<?php

/**
 * @file
 * Module file for the Islandora Repository Reports RDF mappings datasource.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_form_id_alter().
 */
function islandora_repository_reports_rdfmappings_form_islandora_repository_reports_report_selector_alter(&$form, FormStateInterface $form_state, $form_id) {
  $utilities = \Drupal::service('islandora_repository_reports.utilities');
  $bundle_type = $utilities->getFormElementDefault('islandora_repository_reports_rdf_mapping_bundle_type', 'page');

  $node_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('node');
  $node_bundle_options = [];
  foreach ($node_bundles as $name => $attr) {
    $bundle_options[$name] = $attr['label'] . ' (node)';
    $bundle_entity_info[$name] = 'node';
  }

  $media_bundles = \Drupal::service('entity_type.bundle.info')->getBundleInfo('media');
  $media_bundle_options = [];
  foreach ($media_bundles as $name => $attr) {
    $bundle_options[$name] = $attr['label'] . ' (media)';
    $bundle_entity_info[$name] = 'media';
  }

  $form['islandora_repository_reports_rdf_mapping_bundle_type'] = [
    '#type' => 'select',
    '#weight' => 0,
    '#title' => t('Get mappings for'),
    '#default_value' => $bundle_type,
    '#options' => $bundle_options,
    '#states' => [
      'visible' => [
        ':input[name="islandora_repository_reports_report_type"]' => ['value' => 'rdf_mappings'],
      ],
    ],
  ];

  $form['islandora_repository_reports_rdf_mapping_entity_type'] = [
    '#type' => 'value',
    '#value' => serialize($bundle_entity_info),
  ];
}
