<?php

use Drupal\Core\Url;
use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Contains the islandora_repository_reports.module.
 */

/**
 * Implements hook_theme().
 */
function islandora_repository_reports_theme($existing, $type, $theme, $path) {
  return [
    'islandora_repository_reports_chart' => [
      'variables' => ['form' => null, 'show_csv_link' => null],
    ],
  ];
}

/**
 * Default preprocessor function for the islandora_repository_reports_theme hook.
 */
function template_preprocess_islandora_repository_reports_chart(&$variables) {
  $variables['attributes'] = [
    'id' => ['islandora_repository_reports_chart'],
  ];

  if ($tempstore = \Drupal::service('user.private_tempstore')->get('islandora_repository_reports')) {
    $report_type = $tempstore->get('islandora_repository_reports_report_type');
  }
  // Set safe default value.
  if (empty($report_type)) {
    $report_type = 'mimetype';
  }

  if ($variables['show_csv_link']) {
    $files_path = \Drupal::service('file_system')->realpath(file_default_scheme() . "://");
    $filename = 'islandora_repository_reports_' . $report_type . '.csv';
    $report_url = file_create_url(file_default_scheme() . '://' . $filename);
    $variables['csv_url'] = $report_url;
  }
}

/**
 * Implements hook_form_form_id_alter().
 */
function islandora_repository_reports_form_islandora_repository_reports_report_selector_alter(&$form, FormStateInterface $form_state, $form_id) {
  // MIME type report form.
  $media_use_terms = [];
  if ($tempstore = \Drupal::service('user.private_tempstore')->get('islandora_repository_reports')) {
    if ($form_state = $tempstore->get('islandora_repository_reports_report_form_values')) {
      $media_use_terms = $form_state->getValue('islandora_repository_reports_media_use_terms');
    }
  }

  $terms =\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('islandora_media_use');
  $options = [];
  foreach ($terms as $term) {
    $options[$term->tid] = $term->name;
  }
  $form['islandora_repository_reports_media_use_terms'] = [
    '#type' => 'checkboxes',
    '#weight' => 0,
    '#title' => t('Include media with the following Media Use tags:'),
    '#options' => $options,
    '#default_value' => $media_use_terms,
    '#states' => [
      'visible' => [
        ':input[name="islandora_repository_reports_report_type"]' => ['value' => 'mimetype'],
      ],
    ],
  ];

  // Disk usage report form.
  // Default to filesystem if user's choice not available.
  $disk_usage_type = 'filesystem';
  if ($tempstore = \Drupal::service('user.private_tempstore')->get('islandora_repository_reports')) {
    if ($form_state = $tempstore->get('islandora_repository_reports_report_form_values')) {
      $disk_usage_type = $form_state->getValue('islandora_repository_reports_disk_usage_type');
    }
  }

  $form['islandora_repository_reports_disk_usage_type'] = [
    '#type' => 'select',
    '#weight' => 0,
    '#title' => t('Group disk usage by'),
    '#default_value' => $disk_usage_type,
    '#options' => ['filesystem' => t('Drupal filesystem'), 'mimetype' => t('MIME type')],
    '#states' => [
      'visible' => [
        ':input[name="islandora_repository_reports_report_type"]' => ['value' => 'disk_usage'],
      ],
    ],
  ];

}

/**
 * Implements hook_page_attachments().
 */
function islandora_repository_reports_page_attachments(array &$attachments) {
  $current_path = \Drupal::service('path.current')->getPath();
  if ($current_path == '/admin/reports/islandora_repository_reports') {
    if ($tempstore = \Drupal::service('user.private_tempstore')->get('islandora_repository_reports')) {
      $report_type = $tempstore->get('islandora_repository_reports_report_type');
    }
    // Set safe default value.
    if (empty($report_type)) {
      $report_type = 'mimetype';
    }

    $data_source_service_id = 'islandora_repository_reports.datasource.' . $report_type;
    $data_source = \Drupal::service($data_source_service_id);
    $chart_type = $data_source->getChartType();
    if ($chart_type == 'pie') {
      $pie_chart_data = islandora_repository_reports_get_data($report_type);
      $attachments['#attached']['library'][] = 'islandora_repository_reports/islandora_repository_reports_chart';
      $attachments['#attached']['drupalSettings']['islandora_repository_reports']['chart_type'] = 'pie';
      $attachments['#attached']['drupalSettings']['islandora_repository_reports']['chart_title'] = $pie_chart_data['title'];
      $attachments['#attached']['drupalSettings']['islandora_repository_reports']['chart_data'] = $pie_chart_data;
    }
    if ($chart_type == 'bar') {
      $bar_chart_data = islandora_repository_reports_get_data($report_type);
      $attachments['#attached']['library'][] = 'islandora_repository_reports/islandora_repository_reports_chart';
      $attachments['#attached']['drupalSettings']['islandora_repository_reports']['chart_type'] = 'bar';
      $attachments['#attached']['drupalSettings']['islandora_repository_reports']['chart_title'] = $bar_chart_data['title'];
      $attachments['#attached']['drupalSettings']['islandora_repository_reports']['chart_data'] = $bar_chart_data;
    }
  }
}

/**
 * @return object
 *   A Chart.js dataset object.
 */
function islandora_repository_reports_get_data($report_type) {
  $utilities = \Drupal::service('islandora_repository_reports.utilities');

  $config = \Drupal::config('islandora_repository_reports.settings');
  $cache_data = $config->get('islandora_repository_reports_cache_report_data');

  $data_element_counts = &drupal_static(__FUNCTION__);
  $cid = 'islandora_repository_reports_data_' . $report_type;
  if ($cache_data && $cache = \Drupal::cache()->get($cid)) {
    $data_element_counts = $cache->data;
  }
  else {
    $data_source_service_id = 'islandora_repository_reports.datasource.' . $report_type;
    $data_source = \Drupal::service($data_source_service_id);
    $data_element_counts = $data_source->getData();
    if ($cache_data) {
      \Drupal::cache()->set($cid, $data_element_counts);
    }
  }

  // Populate the Chart.js dataset object.
  $num_data_elements = count($data_element_counts);
  $dataset = new StdClass();
  $dataset->data = array_values($data_element_counts);

  if ($data_source->getChartType() == 'pie') {
    if (count($data_element_counts) > 0) {
      $chart_title = t($data_source->getChartTitle(), ['@total' => array_sum($dataset->data)]);
    }
    else {
      $chart_title = t("No @name data available to report on.", ['@name' => $data_source->getName()]);
    }
    $dataset->backgroundColor = $utilities->getChartColors($num_data_elements);
    $chart_data = array(
      'labels' => array_keys($data_element_counts),
      'datasets' =>  array($dataset),
      'title' =>  $chart_title,
    );
  }
  if ($data_source->getChartType() == 'bar') {
    if (count($data_element_counts) > 0) {
      $chart_title = t($data_source->getChartTitle(), ['@total' => array_sum($dataset->data)]);
    }
    else {
      $chart_title = t("No @name data available to report on.", ['@name' => $data_source->getName()]);
    }
    $dataset->label = $data_source->getName();
    $dataset->backgroundColor = '#99b3ff';
    $chart_data = array(
      'labels' => array_keys($data_element_counts),
      'datasets' =>  array($dataset),
      'title' =>  $chart_title,
    );
  }

  // Write out a CSV for download.
  if ($tempstore = \Drupal::service('user.private_tempstore')->get('islandora_repository_reports')) {
    $tempstore->get('islandora_repository_reports_generate_csv');
    $files_path = \Drupal::service('file_system')->realpath(file_default_scheme() . "://");
    $data_source_name = $data_source->getName();
    $csv_data = [[$data_source_name, 'Count']];
    foreach ($data_element_counts as $format => $count) {
      $csv_data[] = [$format, $count];
    }
    $filename = 'islandora_repository_reports_' . $report_type . '.csv';
    $fp = fopen($files_path . '/' . $filename, 'w');
    foreach ($csv_data as $fields) {
      fputcsv($fp, $fields);
    }
    fclose($fp);
  }

  // We're finished with this session variable, so clear it for
  // the next rendering of the report page.
  $tempstore->delete('islandora_repository_reports_generate_csv');
  return $chart_data;
}
