<?php

/**
 * @file
 * Islandora Repository Reports Log module file.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_form_id_alter().
 */
function islandora_repository_reports_log_form_islandora_repository_reports_report_selector_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['#attached']['library'][] = 'islandora_repository_reports/islandora_repository_reports_loading_message';
  $utilities = \Drupal::service('islandora_repository_reports.utilities');

  // Drupal log report type selector element.
  $facet = $utilities->getFormElementDefault('islandora_repository_reports_log_facet', 'type');

  $form['islandora_repository_reports_log_facet'] = [
    '#type' => 'select',
    '#weight' => 0,
    '#title' => t('Group log entries by'),
    '#default_value' => $facet,
    '#options' => [
      'type' => t('Type'),
      'severity' => t('Severity'),
    ],
    '#states' => [
      'visible' => [
        ':input[name="islandora_repository_reports_report_type"]' => ['value' => 'log'],
      ],
    ],
  ];
}
