<?php

/**
 * @file
 * Module file for the Islandora Repository Reports OAI-PMH Usage Report module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_form_id_alter().
 */
function islandora_repository_reports_oai_usage_form_islandora_repository_reports_report_selector_alter(&$form, FormStateInterface $form_state, $form_id) {
  $utilities = \Drupal::service('islandora_repository_reports.utilities');

  // Date range widgets for nodes created by month report.
  $start_of_range = $utilities->getFormElementDefault('islandora_repository_reports_oai_usage_by_month_range_start', '');
  $end_of_range = $utilities->getFormElementDefault('islandora_repository_reports_oai_usage_by_month_range_end', '');

  $form['islandora_repository_reports_oai_usage_by_month_range_start'] = [
    '#type' => 'textfield',
    '#weight' => 0,
    '#size' => 10,
    '#title' => t('Start date'),
    '#default_value' => $start_of_range,
    '#placeholder' => 'yyyy-mm',
    '#description' => t('Limit report to harvests in or after the specified month. Leave empty to include all months up to end date.'),
    '#states' => [
      'visible' => [
        ':input[name="islandora_repository_reports_report_type"]' => [
          ['value' => 'oai_usage'],
        ],
      ],
    ],
  ];

  $form['islandora_repository_reports_oai_usage_by_month_range_end'] = [
    '#type' => 'textfield',
    '#weight' => 0,
    '#size' => 10,
    '#title' => t('End date'),
    '#placeholder' => 'yyyy-mm',
    '#default_value' => $end_of_range,
    '#description' => t('Limit report to harvests up to and including the specified month. Leave empty to include all months after start date.'),
    '#states' => [
      'visible' => [
        ':input[name="islandora_repository_reports_report_type"]' => [
          ['value' => 'oai_usage'],
        ],
      ],
    ],
  ];
}

/**
 * Implements hook_form_form_id_alter().
 */
function islandora_repository_reports_oai_usage_form_islandora_repository_reports_admin_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('islandora_repository_reports_oai_usage.settings');

  $form['oai_usage_settings'] = [
    '#type' => 'fieldset',
    '#title' => t('OAI-PMH harvests report settings'),
  ];
  $form['oai_usage_settings']['islandora_repository_reports_oai_usage_endpoint'] = [
    '#type' => 'textfield',
    '#size' => 50,
    '#title' => t('OAI-PMH endpoint'),
    '#description' => t('Should be the same value as the "Repository path" setting defined by the REST OAI-PMH module.'),
    '#default_value' => $config->get('islandora_repository_reports_oai_usage_endpoint'),
  ];

  $form['#submit'][] = 'islandora_repository_reports_oai_usage_settings_submit';
}

/**
 * Submit callback.
 *
 * Saves the values of fields defined in the form alter hook above.
 *
 * @param array $form
 *   The form.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 */
function islandora_repository_reports_oai_usage_settings_submit(array &$form, FormStateInterface $form_state) {
  $config_factory = \Drupal::configFactory();
  $config_factory->getEditable('islandora_repository_reports_oai_usage.settings')
    ->set('islandora_repository_reports_oai_usage_endpoint', trim($form_state->getValue('islandora_repository_reports_oai_usage_endpoint')))
    ->save();
}
